name: 'Issuekit Action'
description: 'A simple action that helps you comment on issues'
main: 'out/index.js'
inputs:
  token: 
    description: 'GitHub API Authentication Token'
    required: true
  issue: 
    description: 'The issue number to post on. Required if not triggered through a issues webhook event'
    required: false
  issueOverridesWebhook:
    description: 'Whether or not the issue number given should override the one given by the webhook (Defaults to true)'
    required: false
    default: true
  comment: 
    description: 'The comment that should be posted'
    required: false
  assign:
    desctiption: 'Github usernames to assign (comma separated if multiple)'
    required: false
  label: 
    description: 'Label(s) to add (comma separated if multiple)'
    required: false
branding:
  icon: message-square
  color: green
runs:
  using: 'node12'
  main: 'main.js'